# Generated by Django 5.0.6 on 2026-08-14 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('encerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_encerrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventario',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saldo_sistema', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantidade_sistema', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantidade_fisica', models.DecimalField(blank=True, decimal_places=3, help_text='Preenchida durante a contagem física. NULL = ainda não contado.', max_digits=14, null=True)),
                ('divergencia', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('ajuste', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventario.inventario')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_inventario', to='core.material')),
            ],
            options={
                'db_table': 'item_inventario',
            },
        ),
        migrations.CreateModel(
            name='ParticipanteInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('funcao', models.CharField(max_length=50)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='inventario.inventario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participante_inventario',
            },
        ),
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('encerrado_em__isnull', False), ('encerrado_por__isnull', False), ('situacao', 'ENCERRADO')), models.Q(('situacao', 'ENCERRADO'), _negated=True), _connector='OR'), name='ck_inventario_encerramento'),
        ),
        migrations.AddConstraint(
            model_name='iteminventario',
            constraint=models.UniqueConstraint(fields=('inventario', 'material'), name='uq_item_inventario_material'),
        ),
        migrations.AddConstraint(
            model_name='participanteinventario',
            constraint=models.UniqueConstraint(fields=('inventario', 'usuario'), name='uq_participante_inventario'),
        ),
    ]
