# Generated by Django 5.0.6 on 2026-08-14 16:14

import core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('descricao', models.CharField(max_length=300)),
                ('origem', models.CharField(max_length=50)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'demanda',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, validators=[core.validators.validar_telefone])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nome_vendedor', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'fornecedor',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=300)),
                ('fabricante', models.CharField(blank=True, max_length=150, null=True)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, max_digits=14)),
                ('estoque_ideal', models.DecimalField(decimal_places=3, max_digits=14)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('DESCONTINUADO', 'Descontinuado')], default='ATIVO', max_length=20)),
            ],
            options={
                'db_table': 'material',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('DEVOLUCAO', 'Devolução'), ('AJUSTE_INVENTARIO', 'Ajuste de Inventário')], max_length=20)),
                ('quantidade_anterior', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantidade_posterior', models.DecimalField(decimal_places=3, max_digits=14)),
                ('saldo_anterior', models.DecimalField(decimal_places=3, max_digits=14)),
                ('saldo_posterior', models.DecimalField(decimal_places=3, max_digits=14)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_movimentacao', models.DateTimeField()),
            ],
            options={
                'db_table': 'movimentacao',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'perfil',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'posto',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ReferenciaTecnica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Referência Técnica',
                'verbose_name_plural': 'Referências Técnicas',
                'db_table': 'referencia_tecnica',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidade_medida',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, validators=[core.validators.validar_telefone])),
                ('ramal', models.CharField(blank=True, max_length=10, null=True)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('AFASTADO', 'Afastado')], default='ATIVO', max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[core.validators.validar_cpf])),
                ('is_staff', models.BooleanField(default=False, help_text='Acesso ao Django Admin. Independente do perfil de negócio.')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ['nome', 'sobrenome'],
            },
        ),
    ]
