# Generated by Django 5.0.6 on 2026-08-09 17:46

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('devolucoes', '0001_initial'),
        ('entradas', '0001_initial'),
        ('inventario', '0001_initial'),
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='devolucoes.devolucao'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='entradas.entrada'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='item_inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='inventario.iteminventario'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='core.material'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='solicitacoes.solicitacao'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.perfil'),
        ),
        migrations.AddField(
            model_name='posto',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postos_sob_responsabilidade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='posto',
            field=models.ForeignKey(blank=True, help_text='Posto de lotação. Opcional — não confundir com Posto.responsavel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_lotados', to='core.posto'),
        ),
        migrations.AddField(
            model_name='material',
            name='referencia_tecnica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='core.referenciatecnica'),
        ),
        migrations.AddField(
            model_name='material',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiais', to='core.unidademedida'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['material', 'data_movimentacao'], name='movimentaca_materia_011dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['usuario'], name='movimentaca_usuario_9d097f_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.CheckConstraint(check=django.db.models.expressions.RawSQL('(CASE WHEN solicitacao_id     IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN entrada_id         IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN devolucao_id       IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN item_inventario_id IS NOT NULL THEN 1 ELSE 0 END) = 1', output_field=models.BooleanField(), params=[]), name='ck_movimentacao_origem_unica'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(check=models.Q(('estoque_minimo__gte', 0)), name='ck_material_estoque_minimo'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(check=models.Q(('estoque_ideal__gte', models.F('estoque_minimo'))), name='ck_material_estoque_ideal'),
        ),
    ]
