# Generated by Django 5.0.6 on 2026-08-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha_temporaria',
            field=models.BooleanField(default=True, help_text='True enquanto o usuário não trocou a senha inicial gerada pelo sistema.'),
        ),
    ]
