# Generated by Django 5.0.6 on 2026-08-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_material_estoque_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='estoque_minimo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
    ]
