# Generated by Django 5.0.6 on 2026-08-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_material_estoque_minimo_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(check=models.Q(('valor_unitario__gte', 0)), name='ck_material_valor_unitario_nao_negativo'),
        ),
    ]
