# Generated by Django 5.0.6 on 2026-08-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_material_valor_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='responsavel_retirada',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
