# Generated by Django 5.0.6 on 2026-08-14 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('PARCIALMENTE_ATENDIDA', 'Parcialmente atendida'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=25)),
                ('data_solicitacao', models.DateTimeField()),
                ('data_prevista', models.DateTimeField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='core.demanda')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='core.posto')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitacao',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade_solicitada', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantidade_atendida', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('quantidade_devolvida', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('DISPONIVEL', 'Disponível'), ('INDISPONIVEL', 'Indisponível'), ('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_solicitacao', to='core.material')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='solicitacoes.solicitacao')),
            ],
            options={
                'db_table': 'item_solicitacao',
            },
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.CheckConstraint(check=models.Q(('data_prevista__gte', models.F('data_solicitacao'))), name='ck_solicitacao_datas'),
        ),
        migrations.AddConstraint(
            model_name='itemsolicitacao',
            constraint=models.UniqueConstraint(fields=('solicitacao', 'material'), name='uq_item_solicitacao_material'),
        ),
        migrations.AddConstraint(
            model_name='itemsolicitacao',
            constraint=models.CheckConstraint(check=models.Q(('quantidade_solicitada__gt', 0)), name='ck_item_solicitacao_quantidade_solicitada_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itemsolicitacao',
            constraint=models.CheckConstraint(check=models.Q(('quantidade_atendida__gte', 0), ('quantidade_devolvida__gte', 0)), name='ck_item_solicitacao_quantidades_nao_negativas'),
        ),
        migrations.AddConstraint(
            model_name='itemsolicitacao',
            constraint=models.CheckConstraint(check=models.Q(('quantidade_atendida__lte', models.F('quantidade_solicitada'))), name='ck_item_solicitacao_atendida_lte_solicitada'),
        ),
        migrations.AddConstraint(
            model_name='itemsolicitacao',
            constraint=models.CheckConstraint(check=models.Q(('quantidade_devolvida__lte', models.F('quantidade_atendida'))), name='ck_item_solicitacao_devolvida_lte_atendida'),
        ),
    ]
