# Generated by Django 5.0.6 on 2026-08-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='data_prevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
