# Generated by Django 5.0.6 on 2026-08-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_alter_solicitacao_data_prevista'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolicitacao',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
