# Generated by Django 5.0.6 on 2026-08-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_itemsolicitacao_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='reaberta_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
