# Generated by Django 5.0.6 on 2026-08-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_solicitacao_reaberta_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='reaberta_em',
        ),
    ]
