# Generated by Django 5.0.6 on 2026-08-18 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_material_valor_unitario_and_more'),
        ('solicitacoes', '0005_remove_solicitacao_reaberta_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='demanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='core.demanda'),
        ),
    ]
