# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0006_alter_solicitacao_demanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolicitacao',
            name='quantidade_saida_senado',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='itemsolicitacao',
            constraint=models.CheckConstraint(check=models.Q(('quantidade_saida_senado__gte', 0)), name='ck_item_solicitacao_saida_senado_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='itemsolicitacao',
            constraint=models.CheckConstraint(check=models.Q(('quantidade_saida_senado__lte', models.F('quantidade_atendida'))), name='ck_item_solicitacao_saida_senado_lte_atendida'),
        ),
    ]
