# Generated by Django 5.0.6 on 2026-08-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_material_valor_unitario_and_more'),
        ('solicitacoes', '0007_itemsolicitacao_quantidade_saida_senado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolicitacao',
            name='quantidade_separada',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemsolicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('SEPARADO', 'Separado'), ('DISPONIVEL', 'Disponível'), ('INDISPONIVEL', 'Indisponível'), ('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('DISPONIVEL_PARA_RETIRADA', 'Disponível para retirada'), ('PARCIALMENTE_ATENDIDA', 'Parcialmente atendida'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=25),
        ),
        migrations.AddConstraint(
            model_name='itemsolicitacao',
            constraint=models.CheckConstraint(check=models.Q(('quantidade_separada__gte', 0)), name='ck_item_solicitacao_separada_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='itemsolicitacao',
            constraint=models.CheckConstraint(check=models.Q(('quantidade_separada__lte', models.F('quantidade_solicitada'))), name='ck_item_solicitacao_separada_lte_solicitada'),
        ),
    ]
