# Generated by Django 5.0.6 on 2026-08-09 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('condicao', models.BooleanField()),
                ('decisao', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_inicial', models.DateTimeField()),
                ('data_final', models.DateTimeField(blank=True, null=True)),
                ('item_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='solicitacoes.itemsolicitacao')),
                ('responsavel_conferencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes_conferidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devolucao',
                'ordering': ['-data_inicial'],
            },
        ),
        migrations.AddConstraint(
            model_name='devolucao',
            constraint=models.CheckConstraint(check=models.Q(('quantidade__gt', 0)), name='ck_devolucao_quantidade_positiva'),
        ),
    ]
