# Generated by Django 5.0.6 on 2026-08-09 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, null=True)),
                ('data_entrada', models.DateTimeField()),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='core.fornecedor')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entrada',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='ItemEntrada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='entradas.entrada')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_entrada', to='core.material')),
            ],
            options={
                'db_table': 'item_entrada',
            },
        ),
        migrations.AddConstraint(
            model_name='itementrada',
            constraint=models.CheckConstraint(check=models.Q(('quantidade__gt', 0)), name='ck_item_entrada_quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itementrada',
            constraint=models.CheckConstraint(check=models.Q(('valor_unitario__gte', 0), ('valor_total__gte', 0)), name='ck_item_entrada_valores_nao_negativos'),
        ),
    ]
