# Generated by Django 5.0.6 on 2026-08-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='confirmada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
